#ifndef DEBUG_PREFERENCES_H_INCLUDED
#define DEBUG_PREFERENCES_H_INCLUDED

///##############[OBJ_LOADER]######################
//#define DEBUG_OGL_OBJECT_LIFETIME

#endif // DEBUG_PREFERENCES_H_INCLUDED
