#ifndef DEBUG_PREFERENCES_H_INCLUDED
#define DEBUG_PREFERENCES_H_INCLUDED

///##############[OBJ_LOADER]######################

//#define DEBUG_OGL_OBJECT_LIFETIME
#define ENBABLE_LOG_TEXTURE_INFO
//#define ENABLE_DEBUG_KEY_INPUT
//#define ENABLE_DEBUG_MOUSE_BUTTON_INPUT
//#define ENABLE_DEBUG_MOUSE_MOVEMENT
#define ENABLE_DEBUG_WINDOW_RESIZED

#define GEII_DEBUG 1

#define MTL_LOADER_DEBUG_ENABLE 1
#define OBJ_LOADER_DEBUG_ENABLE 1
#define OGL_FRAMEBUFFER_DEBUG_ENABLE 1
#define OGL_SHADER_DEBUG_ENABLE 1
#define OGL_TEXTURE_2D_DEBUG_ENABLE 1
#endif // DEBUG_PREFERENCES_H_INCLUDED
