#ifndef DEBUG_PREFERENCES_H_INCLUDED
#define DEBUG_PREFERENCES_H_INCLUDED

///##############[OBJ_LOADER]######################
//#define DEBUG_OGL_OBJECT_LIFETIME
#define ENBABLE_LOG_TEXTURE_INFO
#define ENABLE_DEBUG_KEY_INPUT
#define ENABLE_DEBUG_MOUSE_BUTTON_INPUT
#define ENABLE_DEBUG_MOUSE_MOVEMENT
#define ENABLE_DEBUG_WINDOW_RESIZED
#endif // DEBUG_PREFERENCES_H_INCLUDED
